apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
      - name: my-angular-app
        image: shaban20/my-angular-app:2e95f03e82bc683f0111dfa10c3f56364c59c7ca
        ports:
        - containerPort: 80
