apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
      - name: my-angular-app
        image: shaban20/my-angular-app:5ecae804abb483657571ced42bbd4057c9730a98
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
