name: Build and Deploy Angular Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build --prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-angular-app:latest

      - name: Commit manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Get the full image name and tag from the build step's output
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/my-angular-app:${{ github.sha }}"

          # Update the image tag in the deployment file
          sed -i "s|image: .*|image: ${IMAGE_TAG}|g" k8s/deployment.yaml

          # Add the modified file, commit, and push
          git add k8s/deployment.yaml
          git commit -m "Update deployment image to ${IMAGE_TAG}"
          git push
